version: '3'
services:
  web:
    image: ssl/server
    container_name: web
    command: ["gunicorn", "ssl_project.wsgi:application", "-b", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - server
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - server

networks:
  server: