version: '3'
services:
  web:
    image: ssl/server
    container_name: web
    command: ["gunicorn", "ssl_project.wsgi:application", "-b", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - server
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - server

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot

networks:
  server: