version: '3'
services:
  web:
    image: ssl/server
    container_name: web
    restart: always
    # command: ["gunicorn", "ssl_project.wsgi:application", "-b", "0.0.0.0:8000"]
    command: bash -c "
      while ! nc -z db 3306; do sleep 1; done 
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn ssl_project.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - server
    depends_on:
      - mysql_db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - server
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ssl
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - server

networks:
  server:

volumes:
  database: